Replacing iconv with iconv-lite
Lynbarry/mvg-api pull request #2
Opened 2017-11-05 11:15 UTC by florian-senn

Other changes may be caused by JetBrains auto-formatting

2017-11-05 11:59 UTC, Lynbarry requested changes
Maybe we shouldn't have the url hardcoded inside the getDepartures-Function at all.

I would propose adding a third parameter to the getDepartures Method, "apiUrl" with a default value of the direct mvg url.

This way it is possible to adjust the endpoint to your needs, but it also defaults to the original url. I'll comment my proposed changes where they would occur.

2017-11-05 11:59 UTC, Lynbarry commented on lib/mvgApi.js
Add a const for the default value here
`const defaultApi = "https://www.mvg-live.de/ims/dfiStaticAuswahl.svc";`

2017-11-05 11:59 UTC, Lynbarry commented on lib/mvgApi.js
>  function getDepartures(station, options) {
Change the signature to 
`function getDepartures(station, options, apiUrl = defaultApi)`

2017-11-05 11:59 UTC, Lynbarry commented on lib/mvgApi.js
> +    const requestUrl = 'https://cors-anywhere.herokuapp.com/https://www.mvg-live.de/ims/dfiStaticAuswahl.svc?haltestelle='.concat(station).concat(transitParams);
Change this to:
`const requestUrl = apiUrl.concat('?haltestelle').concat(station).concat(transitParams);`

2017-11-05 12:01 UTC, Lynbarry commented
Would changing the signature work for you?

I can also do this myself, but I wanted to try out the github pullrequest process to be honest...;)

2017-11-05 12:42 UTC, Lynbarry commented on lib/mvgApi.js
>   */
Documentation for the apiUrl Parameter.

2017-11-06 08:45 UTC, florian-senn commented
Hey Lynbarry, your requested changes are done. Forgot about the URL, after I encountered CORS-errors. The proposed changes are a good feature!

2017-11-06 17:39 UTC, Lynbarry approved these changes

2017-11-06 17:39 UTC, merged